version: '3.0'
services:
  app:
    image: karservice/kobra:latest
    build:
      context: .
    depends_on:
      - postgres
    environment:
      KOBRA_DATABASE_URL: postgres://kobra:kobra-pass@postgres/kobra
      KOBRA_SECRET_KEY: very-secret-key
    ports:
      - 8000:80

  postgres:
    image: sameersbn/postgresql:9.6
    environment:
      DB_USER: kobra
      DB_PASS: kobra-pass
      DB_NAME: kobra
      REPLICATION_MODE: master
      REPLICATION_USER: kobra-replication
      REPLICATION_PASS: kobra-replication-pass
      REPLICATION_SSLMODE: prefer
